# Generated by Django 4.1 on 2023-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comertial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointeam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
