# Generated by Django 4.1 on 2023-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comertial', '0002_alter_jointeam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointeam',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
