# Generated by Django 4.1.5 on 2023-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comertial', '0003_client_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=200)),
                ('questions', models.TextField()),
            ],
        ),
    ]
